### ISSUE TITLE
hacking instructions

### ISSUE THREAD

**Issue by dominictarr** [chrisdickinson/nojs#2]
are those instructions completely correct?

I think you might need to run `gclient config https://github.com/chrisdickinson/nojs.git`
or at least `gclient sync` from inside `nojs` repo

**Comment by dominictarr** [comment]
okay no that ran into problems, for some reason it didn't seem to download v8.
i deleted my `nojs` dir and am trying again...

**Comment by dominictarr** [comment]
ah, no the problem was that since I am running on a simple docker image it didn't have things that scripts expected to exist (like `curl`) but they didn't error in a friendly way.

**Comment by dominictarr** [comment]
ah, and now there is another problem just like that one...
```
ERROR at //build/config/linux/pkg_config.gni:86:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/nojs/out/Default/
Command: python -- /home/nojs/build/config/linux/pkg-config.py -s /home/nojs/build/linux/debian_wheezy_amd64-sysroot -a x64 --system_libdir lib freetype2
Returned 1.
stderr:

Traceback (most recent call last):
  File "/home/nojs/build/config/linux/pkg-config.py", line 219, in <module>
    sys.exit(main())
  File "/home/nojs/build/config/linux/pkg-config.py", line 138, in main
    prefix = GetPkgConfigPrefixToStrip(args)
  File "/home/nojs/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
why is it `//build` is that right?

**Comment by chrisdickinson** [comment]
I'm hacking through this concurrently on a trusty box. The build bits are from chromium, so there's cruft to rip out — in this case, `pkg-config` is totally unnecessary.

I just got it building on trusty five minutes ago and am retracing my steps to make sure I've got it.

**Comment by dominictarr** [comment]
Sounds great!
